import { motion } from 'framer-motion'

export default function NarrativeSummary({ summary }) {
  if (!summary) return null

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.6, duration: 0.5 }}
      className="bg-white rounded-xl shadow-lg p-8"
    >
      <h3 className="text-2xl font-bold text-slate-800 mb-4">
        📖 What Patients Reported (AI Summary)
      </h3>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.7 }}
        className="bg-gradient-to-br from-primary/5 to-secondary/5 rounded-lg p-6 border-l-4 border-primary"
      >
        <p className="text-slate-700 leading-relaxed text-lg">
          {summary}
        </p>
      </motion.div>

      <p className="text-xs text-slate-500 mt-4">
        Summary generated by Claude AI based on FAERS patient narratives
      </p>
    </motion.div>
  )
}
